package aicore.unit.model;

import java.util.stream.Stream;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import com.microsoft.playwright.Page;

import aicore.pages.home.MainMenuUtils;
import aicore.pages.model.AddModelFormUtils;
import aicore.utils.AbstractPlaywrightTestBase;
import aicore.utils.CatlogAccessPageUtility;
import aicore.utils.CommonUtils;
import aicore.utils.ModelTestUtils;
import aicore.utils.annotations.PWPage;
import aicore.utils.page.model.ModelPageUtils;

public class AddAllModelsTests extends AbstractPlaywrightTestBase {

	@BeforeEach
	void setup(@PWPage Page page) {
		// login with admin user before tests
		loginNativeAdmin(page);
	}

	private Stream<Arguments> provideModelCreationCases() {
		return Stream.of(
				Arguments.of(
						"OpenAI",
						"chatgpt-image-latest",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Chat GPT Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Chat GPT Model",
						"NAME=Chat GPT Model, MODEL=chatgpt-image-latest, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"OpenAI",
						"GPT Image 1.5",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT Image, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT Image",
						"NAME=GPT Image, MODEL=gpt-image-1.5, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT Image 1",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT Image, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT Image",
						"NAME=GPT Image, MODEL=gpt-image-1, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"gpt-image-1-mini",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT Image Mini, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT Image Mini",
						"NAME=GPT Image Mini, MODEL=gpt-image-1-mini, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT-5",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT-5-Model",
						"NAME=GPT-5-Model, MODEL=gpt-5, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT-4.1",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-4-Model, Chat Type=chat-completion, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=30, Context Window=2048, Record Questions and Responses=true, Keep Conversation History=true",
						"GPT-4-Model",
						"NAME=GPT-4-Model, MODEL=gpt-4.1, CHAT_TYPE=chat-completion, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=2048, MAX_TOKENS=30"),
				Arguments.of(
						"OpenAI",
						"GPT-5 Mini",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-Mini-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=40, Context Window=1000, Record Questions and Responses=false, Keep Conversation History=true",
						"GPT-5-Mini-Model",
						"NAME=GPT-5-Mini-Model, MODEL=gpt-5-mini, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=1000, MAX_TOKENS=40"),
				Arguments.of(
						"OpenAI",
						"GPT-5 nano",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-Nano-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=50, Context Window=1000, Record Questions and Responses=false, Keep Conversation History=true",
						"GPT-5-Nano-Model",
						"NAME=GPT-5-Nano-Model, MODEL=gpt-5-nano, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=1000, MAX_TOKENS=50"),
				Arguments.of(
						"OpenAI",
						"GPT-5.1",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-1-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT-5-1-Model",
						"NAME=GPT-5-1-Model, MODEL=gpt-5.1, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT-5.4",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-4-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT-5-4-Model",
						"NAME=GPT-5-4-Model, MODEL=gpt-5.4, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT-5.4 Mini",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-4-Mini-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT-5-4-Mini-Model",
						"NAME=GPT-5-4-Mini-Model, MODEL=gpt-5.4-mini, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT-5.4 Nano",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-4-Nano-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT-5-4-Nano-Model",
						"NAME=GPT-5-4-Nano-Model, MODEL=gpt-5.4-nano, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"GPT-5.4 Pro",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=GPT-5-4-Pro-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"GPT-5-4-Pro-Model",
						"NAME=GPT-5-4-Pro-Model, MODEL=gpt-5.4-pro, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"text-embedding-3-large",
						"General",
						"Catalog Name, Model, Tag",
						"Credentials",
						"OpenAI API Key",
						"Settings",
						"Max Tokens, Record Questions and Responses, Init Script",
						"Catalog Name, Model, Tag, OpenAI API Key, Record Questions and Responses, Init Script",
						"Catalog Name=text-embedding-large, OpenAI API Key=Test123, Max Tokens=9, Record Questions and Responses=false",
						"text-embedding-large",
						"NAME=text-embedding-large, MODEL=text-embedding-3-large, INIT_MODEL_ENGINE=from genai_client import OpenAiE, KEEP_INPUT_OUTPUT=false, MAX_TOKENS=9, TAG=embeddings"),
				Arguments.of(
						"OpenAI",
						"text-embedding-3-small",
						"General",
						"Catalog Name, Model, Tag",
						"Credentials",
						"OpenAI API Key",
						"Settings",
						"Max Tokens, Record Questions and Responses, Init Script",
						"Catalog Name, Model, Tag, OpenAI API Key, Record Questions and Responses, Init Script",
						"Catalog Name=text-embedding-small, OpenAI API Key=Test123, Max Tokens=19, Record Questions and Responses=false",
						"text-embedding-small",
						"NAME=text-embedding-small, MODEL=text-embedding-3-small, INIT_MODEL_ENGINE=from genai_client import OpenAiE, KEEP_INPUT_OUTPUT=false, MAX_TOKENS=19, TAG=embeddings"),
				Arguments.of(
						"OpenAI",
						"Other OpenAI Model",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Open AI Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Other Open Ai Model, Model=Other Open Ai, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false",
						"Other Open Ai Model",
						"NAME=Other Open Ai Model, MODEL=Other Open Ai, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20"),
				Arguments.of(
						"OpenAI",
						"Other OpenAI Embedding Model",
						"General",
						"Catalog Name, Model, Tag",
						"Credentials",
						"OpenAI API Key",
						"Settings",
						"Max Tokens, Record Questions and Responses, Init Script",
						"Catalog Name, Model, Tag, OpenAI API Key, Record Questions and Responses, Init Script",
						"Catalog Name=Other Open Ai Embedding, Model=Other Open Ai Embedding, OpenAI API Key=Test123, Max Tokens=9, Record Questions and Responses=false",
						"Other Open Ai Embedding",
						"NAME=Other Open Ai Embedding, MODEL=Other Open Ai Embedding, INIT_MODEL_ENGINE=from genai_client import OpenAiE, KEEP_INPUT_OUTPUT=false, MAX_TOKENS=9, TAG=embeddings"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Opus 4.6 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Opus, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Opus",
						"NAME=Claude Opus, MODEL=anthropic.claude-opus-4-6-v1, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Sonnet 4.6 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Sonnet, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Sonnet",
						"NAME=Claude Sonnet, MODEL=anthropic.claude-sonnet-4-6, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Sonnet 4.5 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Sonnet, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Sonnet",
						"NAME=Claude Sonnet, MODEL=anthropic.claude-sonnet-4-5-20250929-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Haiku 4.5 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Haiku, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Haiku",
						"NAME=Claude Haiku, MODEL=anthropic.claude-haiku-4-5-20251001-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Opus 4.5 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Opus, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Opus",
						"NAME=Claude Opus, MODEL=anthropic.claude-opus-4-5-20251101-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Sonnet 4 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Sonnet, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Sonnet",
						"NAME=Claude Sonnet, MODEL=anthropic.claude-sonnet-4-20250514-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude Opus 4.1 (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Opus, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Opus",
						"NAME=Claude Opus, MODEL=anthropic.claude-opus-4-1-20250805-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Claude 3.5 Haiku (Bedrock)",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Provider, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Haiku, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Haiku",
						"NAME=Claude Haiku, MODEL=anthropic.claude-3-5-haiku-20241022-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova 2 Lite",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-2-lite-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova 2 Sonic",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-2-sonic-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Canvas",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-canvas-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Lite",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-lite-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Micro",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-micro-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Premier",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-premier-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Pro",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-pro-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Reel",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-reel-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Reel v1.1",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-reel-v1:1, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Nova Sonic",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Nova, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Nova",
						"NAME=Amazon Nova, MODEL=amazon.nova-sonic-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Rerank 1.0",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Rerank, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Rerank",
						"NAME=Amazon Rerank, MODEL=amazon.rerank-v1:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Titan Image Generator G1 v2",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Titan, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Titan",
						"NAME=Amazon Titan, MODEL=amazon.titan-image-generator-v2:0, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Amazon Titan Text Large",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Amazon Titan, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Amazon Titan",
						"NAME=Amazon Titan, MODEL=amazon.titan-tg1-large, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"AWS Bedrock",
						"Other AWS Bedrock Model",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"AWS Access Key, AWS Secret Access Key, Region",
						"Settings",
						"Record Questions and Responses, Keep Conversation History, Max Completion Tokens, Context Window, Init Script",
						"Catalog Name, Model ID, Region, AWS Access Key, AWS Secret Access Key, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Other AWS Bedrock, Model ID=Other AWS Bedrock, AWS Access Key=123, AWS Secret Access Key=Test@123, Region=Asia, Max Completion Tokens=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Other AWS Bedrock",
						"NAME=Other AWS Bedrock, MODEL=Other AWS Bedrock, AWS_REGION=Asia, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Anthropic",
						"Claude Haiku 4.5",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"API Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Provider, API Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Claude Haiku Model, API Key=Test123, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Claude Haiku Model",
						"NAME=Claude Haiku Model, MODEL=claude-haiku-4-5-20251001, PROVIDER=anthropic, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Anthropic",
						"Claude Opus 4.6",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"API Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Provider, API Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Claude Opus Model, API Key=Test123, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Claude Opus Model",
						"NAME=Claude Opus Model, MODEL=claude-opus-4-6, PROVIDER=anthropic, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Anthropic",
						"Claude Sonnet 4.6",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"API Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Provider, API Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Claude Sonnet Model, API Key=Test123, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Claude Sonnet Model",
						"NAME=Claude Sonnet Model, MODEL=claude-sonnet-4-6, PROVIDER=anthropic, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Anthropic",
						"Other Anthropic Model",
						"General",
						"Catalog Name, Model ID, Provider",
						"Credentials",
						"API Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Provider, API Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Other Anthropic Model, Model ID=Other Anthropic Model, API Key=Test123, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Other Anthropic Model",
						"NAME=Other Anthropic Model, MODEL=Other Anthropic Model, PROVIDER=anthropic, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"NVIDIA NIM",
						"EMBED QA 4",
						"General",
						"Catalog Name, Model Name",
						"Credentials",
						"API Key, Endpoint",
						"Settings",
						"Record Questions and Responses, Keep Conversation History",
						"Catalog Name, Model Name, API Key, Endpoint, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Embeded QA Model, API Key=Test123, Endpoint=https://www.google.com/, Record Questions and Responses=false, Keep Conversation History=false",
						"Embeded QA Model",
						"NAME=Embeded QA Model, MODEL=embed-qa-4, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false"),
				Arguments.of(
						"Azure OpenAI",
						"Azure Open AI",
						"General",
						"Catalog Name, Model (Deployment Name), Chat Type",
						"Credentials",
						"Azure Endpoint, Azure Open AI Key, API Version",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model (Deployment Name), Chat Type, Azure Endpoint, Azure Open AI Key, API Version, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Azure OpenAi Model, Model (Deployment Name)=ModelDeploymentName, Chat Type=responses, Azure Endpoint=https://www.google.com/, Azure Open AI Key=Abc123, API Version=v5, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Azure OpenAi Model",
						"NAME=Azure OpenAi Model, MODEL=ModelDeploymentName, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Azure OpenAI",
						"Claude (Azure)",
						"General",
						"Catalog Name, Model, Provider",
						"Credentials",
						"Azure Endpoint, API Key",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Provider, Azure Endpoint, API Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Claude Azure Model, Model=ModelClaudeName, Azure Endpoint=https://www.google.com/, API Key=v125, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Claude Azure Model",
						"NAME=Claude Azure Model, MODEL=ModelClaudeName, PROVIDER=azure, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Azure OpenAI",
						"Other Azure OpenAI Model",
						"General",
						"Catalog Name, Model, Chat Type",
						"Credentials",
						"Azure Endpoint, Azure Open AI Key, API Version",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Chat Type, Azure Endpoint, Azure Open AI Key, API Version, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History",
						"Catalog Name=Other Azure OpenAi Model, Model=OtherModelName, Chat Type=responses, Azure Endpoint=https://www.google.com/, Azure Open AI Key=Abc123, API Version=v5, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Other Azure OpenAi Model",
						"NAME=Other Azure OpenAi Model, MODEL=OtherModelName, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Google Gemini",
						"Claude Haiku 4.5 (Vertex)",
						"General",
						"Catalog Name, Model, Provider",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Provider, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Haiku Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Haiku Model",
						"NAME=Claude Haiku Model, MODEL=claude-haiku-4-5@20251001, PROVIDER=google, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Claude Opus 4.6 (Vertex)",
						"General",
						"Catalog Name, Model, Provider",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Provider, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Opus Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Opus Model",
						"NAME=Claude Opus Model, MODEL=claude-opus-4-6, PROVIDER=google, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Claude Sonnet 4.6 (Vertex)",
						"General",
						"Catalog Name, Model, Provider",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Provider, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Claude Sonnet Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Claude Sonnet Model",
						"NAME=Claude Sonnet Model, MODEL=claude-sonnet-4-6, PROVIDER=google, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 3.1 Pro Preview",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini pro Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini pro Model",
						"NAME=Gemini pro Model, MODEL=gemini-3.1-pro-preview, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 3 Flash Preview",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash Model",
						"NAME=Gemini flash Model, MODEL=gemini-3-flash-preview, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 3.1 Flash Lite Preview",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash lite Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash lite Model",
						"NAME=Gemini flash lite Model, MODEL=gemini-3.1-flash-lite-preview, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 3 Pro Image Preview",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini pro image Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini pro image Model",
						"NAME=Gemini pro image Model, MODEL=gemini-3-pro-image-preview, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 3.1 Flash Image Preview",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash image Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash image Model",
						"NAME=Gemini flash image Model, MODEL=gemini-3.1-flash-image-preview, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 2.5 Pro",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini pro Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini pro Model",
						"NAME=Gemini pro Model, MODEL=gemini-2.5-pro, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 2.5 Flash",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash Model",
						"NAME=Gemini flash Model, MODEL=gemini-2.5-flash, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 2.5 Flash Lite",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash Model",
						"NAME=Gemini flash Model, MODEL=gemini-2.5-flash-lite, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 2.0 Flash 001",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash Model",
						"NAME=Gemini flash Model, MODEL=gemini-2.0-flash-001, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Gemini 2.5 Flash Image",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Gemini flash Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Gemini flash Model",
						"NAME=Gemini flash Model, MODEL=gemini-2.5-flash-image, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Google Gemini",
						"Other Google Gemini Model",
						"General",
						"Catalog Name, Model",
						"Credentials",
						"Project, GCP Region, Service Account Credentials",
						"Settings",
						"Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model, Project, GCP Region, Service Account Credentials, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Other Google Gemini Model, Model=Other Google Gemini Model, Project=projectABC, GCP Region=Abc123, Service Account Credentials=PQR, Max Tokens (Max Completion Tokens)=22, Context Window=2200, Record Questions and Responses=false, Keep Conversation History=true",
						"Other Google Gemini Model",
						"NAME=Other Google Gemini Model, MODEL=Other Google Gemini Model, PROJECT=projectABC, GCP_REGION=Abc123, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=2200, MAX_TOKENS=22"),
				Arguments.of(
						"Perplexity",
						"Sonar",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"Perplexity API Key, Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Perplexity API Key, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Sonar Model, Perplexity API Key=ABC123, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Sonar Model",
						"NAME=Sonar Model, MODEL=sonar, ENDPOINT=https://api.perplexity.ai, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Perplexity",
						"Sonar Pro",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"Perplexity API Key, Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Perplexity API Key, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Sonar Pro Model, Perplexity API Key=ABC123, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Sonar Pro Model",
						"NAME=Sonar Pro Model, MODEL=sonar-pro, ENDPOINT=https://api.perplexity.ai, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Perplexity",
						"Sonar Reasoning Pro",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"Perplexity API Key, Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Perplexity API Key, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Sonar Reasoning Pro Model, Perplexity API Key=ABC123, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Sonar Reasoning Pro Model",
						"NAME=Sonar Reasoning Pro Model, MODEL=sonar-reasoning-pro, ENDPOINT=https://api.perplexity.ai, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Perplexity",
						"Sonar Deep Research",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"Perplexity API Key, Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Perplexity API Key, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Sonar Deep Research Model, Perplexity API Key=ABC123, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Sonar Deep Research Model",
						"NAME=Sonar Deep Research Model, MODEL=sonar-deep-research, ENDPOINT=https://api.perplexity.ai, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Perplexity",
						"Other Perplexity Model",
						"General",
						"Catalog Name, Model ID",
						"Credentials",
						"Perplexity API Key, Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Model ID, Perplexity API Key, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Other Perplexity Model, Model ID=other-perplexity, Perplexity API Key=ABC123, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Other Perplexity Model",
						"NAME=Other Perplexity Model, MODEL=other-perplexity, ENDPOINT=https://api.perplexity.ai, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Falcon",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Falcon Model, Model Name=falcon, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Falcon Model",
						"NAME=Falcon Model, MODEL=falcon, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Flan T5 Large",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Flan T5 Large Model, Model Name=flan t5, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Flan T5 Large Model",
						"NAME=Flan T5 Large Model, MODEL=flan t5, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Flan T5 XXL",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Flan T5 XXL Model, Model Name=flan t5, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Flan T5 XXL Model",
						"NAME=Flan T5 XXL Model, MODEL=flan t5, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Llama3 405B",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Llama3 405B Model, Model Name=llama3, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Llama3 405B Model",
						"NAME=Llama3 405B Model, MODEL=llama3, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Llama3 70B",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Llama3 70B Model, Model Name=llama3, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Llama3 70B Model",
						"NAME=Llama3 70B Model, MODEL=llama3, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Llama3 8B",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Llama3 8B Model, Model Name=llama3, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Llama3 8B Model",
						"NAME=Llama3 8B Model, MODEL=llama3, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Mosaic ML",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Mosaic ML Model, Model Name=mosaicml, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Mosaic ML Model",
						"NAME=Mosaic ML Model, MODEL=mosaicml, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Replit code model – 3b",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Replit code Model, Model Name=replitcode, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Replit code Model",
						"NAME=Replit code Model, MODEL=replitcode, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Other Self Hosted Model",
						"General",
						"Catalog Name, Chat Type, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name, Chat Type, Deployment Type, Model Name, Endpoint, Max Completion Tokens, Context Window, Record Questions and Responses, Keep Conversation History, Init Script",
						"Catalog Name=Other Self Hosted Model, Model Name=otherselfhosted, Endpoint=https://www.google.com/, Max Completion Tokens=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false",
						"Other Self Hosted Model",
						"NAME=Other Self Hosted Model, MODEL=otherselfhosted, CHAT_TYPE=chat-completion, DEPLOYMENT_TYPE=vLLM, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10"),
				Arguments.of(
						"Self Hosted",
						"Other Self Hosted Embedding Model",
						"General",
						"Catalog Name, Deployment Type, Model Name",
						"Credentials",
						"Endpoint",
						"Settings",
						"Record Questions and Responses, Init Script",
						"Catalog Name, Deployment Type, Model Name, Endpoint, Record Questions and Responses, Init Script",
						"Catalog Name=Other Self Hosted Embedding Model, Model Name=otherselfhostedembedding, Endpoint=https://www.google.com/, Record Questions and Responses=true",
						"Other Self Hosted Embedding Model",
						"NAME=Other Self Hosted Embedding Model, MODEL=otherselfhostedembedding, DEPLOYMENT_TYPE=TGI, ENDPOINT=https://www.google.com/, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}"));
	}

	@ParameterizedTest(name = "[{index}] {0} -> {1}")
	@MethodSource("provideModelCreationCases")
	public void testAddModelType(String group, String model, String s1Name, String s1Fields, String s2Name,
			String s2Fields, String s3Name, String s3Fields, String mandatoryFields, String formFields,
			String catalogName, String smssFields, @PWPage Page page) {
		String timestamp = CommonUtils.getTimeStampName();

		openAddModelForm(page, group, model);
		ModelTestUtils.verifyFormSections(page,
				ModelTestUtils.buildSections(s1Name, s1Fields, s2Name, s2Fields, s3Name, s3Fields));
		ModelTestUtils.verifyMandatoryFields(page, mandatoryFields);
		ModelTestUtils.fillModelCreationForm(page, formFields, timestamp);
		Assertions.assertTrue(AddModelFormUtils.validateConnectButtonEnabled(page), "'Create Model' button is not enabled");

		AddModelFormUtils.clickOnCreateModelButton(page, "Create Model");
		Assertions.assertEquals("Successfully added LLM to catalog",
				ModelPageUtils.modelCreationToastMessage(page, "Successfully added LLM to catalog"));

		CatlogAccessPageUtility.getCatalogAndCopyId(page);
		Assertions.assertEquals(catalogName + timestamp, ModelPageUtils.verifyModelTitle(page, catalogName + timestamp));
		ModelPageUtils.clickOnSMSSTab(page);
		ModelTestUtils.verifySmssFields(page, smssFields);
		CommonUtils.navigateAndDeleteCatalog(page, "Model", catalogName + timestamp);
		logout(page);
	}

	private void openAddModelForm(Page page, String group, String model) {
		MainMenuUtils.openMainMenu(page);
		MainMenuUtils.clickOnOpenModel(page);
		ModelPageUtils.clickAddModelButton(page);
		AddModelFormUtils.clickOnGroupTab(page, group);
		AddModelFormUtils.selectModel(page, model);
	}
}
