name: e2e
services:
  semoss:
    build:
      context: ds2
    ports:
      - "9091:8080"
    network_mode: "host"
    #    environment:
    #      - SETSOCIAL=true
    #      - ENABLE_NATIVE=true
    #      - ENABLE_NATIVE_REGISTRATION=true
    command: /bin/bash -c "/app/scripts.sh"
#    networks:
#      - tnet
    #    volumes:
    #      - ./results/coverage:/opt/testresults/

  test:
    build: .
    depends_on:
      - semoss
    volumes:
      - .:/workspace
    working_dir: /workspace
    ipc: host
    network_mode: "host"
    cap_add:
      - SYS_ADMIN
#    networks:
#      - tnet
    user: "${UID}:${GID}"  # Run the container as the current user
#
#networks:
#  tnet:


