@LoginWithAdmin @Regression @DeleteTestCatalog
Feature: Add all model types

  Scenario Outline: Create '<MODEL>' model and validate its SMSS properties
    Given User opens Main Menu
    When User clicks on Open Model
    And User clicks on Add Model
    And User clicks on the '<GROUP>' tab
    And User selects '<MODEL>'
    Then User can see following form sections with fields:
      | SECTION_NAME | FIELDS      |
      | <S1_NAME>    | <S1_FIELDS> |
      | <S2_NAME>    | <S2_FIELDS> |
      | <S3_NAME>    | <S3_FIELDS> |
    And User can see following fields are mandatory fields
      | <MANDATORY_FIELDS> |
    When User fills the model creation form with:
      | <FORM_FIELDS> |
    Then User can see 'Create Model' button becomes enabled
    When User clicks on model 'Create Model' button
    #Then User can see a toast message as 'Successfully added LLM to catalog'
    When User clicks on Copy Catalog ID
    Then User can see the Model title as '<CATALOG_NAME>'
    When User clicks on SMSS
    Then User can see following fields in SMSS Properties
      | <SMSS_FIELDS> |

    Examples: 
      | GROUP  | MODEL                        | S1_NAME | S1_FIELDS                      | S2_NAME     | S2_FIELDS      | S3_NAME  | S3_FIELDS                                                                                                                  | MANDATORY_FIELDS                                                                                                                                           | FORM_FIELDS                                                                                                                                                                                                                       | CATALOG_NAME            | SMSS_FIELDS                                                                                                                                                                                                           |
      | OpenAI | chatgpt-image-latest         | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=Chat GPT Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=10, Context Window=5000, Record Questions and Responses=false, Keep Conversation History=false                          | Chat GPT Model          | NAME=Chat GPT Model, MODEL=chatgpt-image-latest, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=5000, MAX_TOKENS=10 |
      | OpenAI | GPT Image 1.5                | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT Image, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                                | GPT Image               | NAME=GPT Image, MODEL=gpt-image-1.5, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20              |
      | OpenAI | GPT Image 1                  | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT Image, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                                | GPT Image               | NAME=GPT Image, MODEL=gpt-image-1, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20                |
      | OpenAI | gpt-image-1-mini             | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT Image Mini, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                           | GPT Image Mini          | NAME=GPT Image Mini, MODEL=gpt-image-1-mini, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20      |
      | OpenAI | GPT-5                        | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                              | GPT-5-Model             | NAME=GPT-5-Model, MODEL=gpt-5, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20                    |
      | OpenAI | GPT-4.1                      | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-4-Model, Chat Type=chat-completion, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=30, Context Window=2048, Record Questions and Responses=true, Keep Conversation History=true                         | GPT-4-Model             | NAME=GPT-4-Model, MODEL=gpt-4.1, CHAT_TYPE=chat-completion, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=2048, MAX_TOKENS=30             |
      | OpenAI | GPT-5 Mini                   | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-Mini-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=40, Context Window=1000, Record Questions and Responses=false, Keep Conversation History=true                         | GPT-5-Mini-Model        | NAME=GPT-5-Mini-Model, MODEL=gpt-5-mini, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=1000, MAX_TOKENS=40          |
      | OpenAI | GPT-5 nano                   | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-Nano-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=50, Context Window=1000, Record Questions and Responses=false, Keep Conversation History=true                         | GPT-5-Nano-Model        | NAME=GPT-5-Nano-Model, MODEL=gpt-5-nano, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=true, KEEP_INPUT_OUTPUT=false, CONTEXT_WINDOW=1000, MAX_TOKENS=50          |
      | OpenAI | GPT-5.1                      | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-1-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                            | GPT-5-1-Model           | NAME=GPT-5-1-Model, MODEL=gpt-5.1, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20                |
      | OpenAI | GPT-5.4                      | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-4-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                            | GPT-5-4-Model           | NAME=GPT-5-4-Model, MODEL=gpt-5.4, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20                |
      | OpenAI | GPT-5.4 Mini                 | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-4-Mini-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                       | GPT-5-4-Mini-Model      | NAME=GPT-5-4-Mini-Model, MODEL=gpt-5.4-mini, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20      |
      | OpenAI | GPT-5.4 Nano                 | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-4-Nano-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                       | GPT-5-4-Nano-Model      | NAME=GPT-5-4-Nano-Model, MODEL=gpt-5.4-nano, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20      |
      | OpenAI | GPT-5.4 Pro                  | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=GPT-5-4-Pro-Model, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false                        | GPT-5-4-Pro-Model       | NAME=GPT-5-4-Pro-Model, MODEL=gpt-5.4-pro, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20        |
      | OpenAI | text-embedding-3-large       | General | Catalog Name, Model, Tag       | Credentials | OpenAI API Key | Settings | Max Tokens, Record Questions and Responses, Init Script                                                                    | Catalog Name, Model, Tag, OpenAI API Key, Record Questions and Responses, Init Script                                                                      | Catalog Name=text-embedding-large, OpenAI API Key=Test123, Max Tokens=9, Record Questions and Responses=false                                                                                                                     | text-embedding-large    | NAME=text-embedding-large, MODEL=text-embedding-3-large, INIT_MODEL_ENGINE=from genai_client import OpenAiE, KEEP_INPUT_OUTPUT=false, MAX_TOKENS=9, TAG=embeddings                                                    |
      | OpenAI | text-embedding-3-small       | General | Catalog Name, Model, Tag       | Credentials | OpenAI API Key | Settings | Max Tokens, Record Questions and Responses, Init Script                                                                    | Catalog Name, Model, Tag, OpenAI API Key, Record Questions and Responses, Init Script                                                                      | Catalog Name=text-embedding-small, OpenAI API Key=Test123, Max Tokens=19, Record Questions and Responses=false                                                                                                                    | text-embedding-small    | NAME=text-embedding-small, MODEL=text-embedding-3-small, INIT_MODEL_ENGINE=from genai_client import OpenAiE, KEEP_INPUT_OUTPUT=false, MAX_TOKENS=19, TAG=embeddings                                                   |
      | OpenAI | Other OpenAI Model           | General | Catalog Name, Model, Chat Type | Credentials | Open AI Key    | Settings | Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History, Init Script | Catalog Name, Model, Chat Type, Open AI Key, Max Tokens (Max Completion Tokens), Context Window, Record Questions and Responses, Keep Conversation History | Catalog Name=Other Open Ai Model, Model=Other Open Ai, Chat Type=responses, Open AI Key=Test123, Max Tokens (Max Completion Tokens)=20, Context Window=5001, Record Questions and Responses=true, Keep Conversation History=false | Other Open Ai Model     | NAME=Other Open Ai Model, MODEL=Other Open Ai, CHAT_TYPE=responses, INIT_MODEL_ENGINE=import genai_client;${VAR_NAME}, KEEP_CONVERSATION_HISTORY=false, KEEP_INPUT_OUTPUT=true, CONTEXT_WINDOW=5001, MAX_TOKENS=20    |
      | OpenAI | Other OpenAI Embedding Model | General | Catalog Name, Model, Tag       | Credentials | OpenAI API Key | Settings | Max Tokens, Record Questions and Responses, Init Script                                                                    | Catalog Name, Model, Tag, OpenAI API Key, Record Questions and Responses, Init Script                                                                      | Catalog Name=Other Open Ai Embedding, Model=Other Open Ai Embedding, OpenAI API Key=Test123, Max Tokens=9, Record Questions and Responses=false                                                                                   | Other Open Ai Embedding | NAME=Other Open Ai Embedding, MODEL=Other Open Ai Embedding, INIT_MODEL_ENGINE=from genai_client import OpenAiE, KEEP_INPUT_OUTPUT=false, MAX_TOKENS=9, TAG=embeddings                                                |
