Feature: verify all database types with its fields

  Scenario Outline: Verify <DATABASE> database types with its fields
    Given User opens Main Menu
    When User clicks on Open Database
    And User clicks on Add Database
    And User selects database '<DATABASE>' from connection types
    Then User can see form sections with fields:
      | SECTION_NAME | FIELDS      |
      | <S1_NAME>    | <S1_FIELDS> |
      | <S2_NAME>    | <S2_FIELDS> |
      | <S3_NAME>    | <S3_FIELDS> |
      | <S4_NAME>    | <S4_FIELDS> |
    And User can see database mandatory fields
      | <MANDATORY_FIELDS> |

    Examples: 
      | DATABASE       | S1_NAME | S1_FIELDS                                | S2_NAME  | S2_FIELDS                                                                                             | S3_NAME     | S3_FIELDS                                                    | S4_NAME           | S4_FIELDS                                                    | MANDATORY_FIELDS                                                    |
      | Aster          | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Athena         | General | Catalog Name, Database Description, Tags | Settings | Region, Output, Schema, Additional Parameters, JDBC Url                                               | Credentials | Access Key, Secret Key                                       | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Output, Access Key, Secret Key                        |
      | BigQuery       | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Project, Schema, Additional Parameters, JDBC Url                                     | Credentials | OAuth Type, OAuth Service Account, OAuth Service Account Key | Advanced Settings | Not Available                                                | Catalog Name, Project, OAuth Type                                   |
      | Cassandra      | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | ClickHouse     | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Database, Schema, Additional Parameters, JDBC Url                                    | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | DATABRICKS     | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, HTTP Path, Database, Schema, Additional Parameters, JDBC Url                         | Credentials | UID, Personal Access Token                                   | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, HTTP Path, UID                             |
      | DataStax       | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, GRAPH                                                                                | Credentials | Username, Password                                           | Advanced Settings | Not Available                                                | Catalog Name, Host Name, GRAPH                                      |
      | DB2            | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Derby          | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Elastic Search | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, HTTP Type, Additional Parameters, JDBC Url                                           | Credentials | Username, Password                                           | Advanced Settings | Not Available                                                | Catalog Name, Host Name                                             |
      | H2             | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Schema, JDBC Url                           |
      | Hive           | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Impala         | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | MariaDB        | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | MySQL          | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Open Search    | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, HTTP Path, Additional Parameters, JDBC Url                                           | Credentials | Username, Password                                           | Advanced Settings | Not Available                                                | Catalog Name, Host Name                                             |
      | Oracle         | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, SID Service, Additional Parameters, JDBC Url                                         | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Phoenix        | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Postgres       | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Database, Schema, Additional Parameters, JDBC Url                                    | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Database                                   |
      | Redshift       | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Database, Schema, Additional Parameters, JDBC Url                                    | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Database                                   |
      | SAP Hana       | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Schema                                     |
      | SEMOSS         | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Project Id, Insight Id, Endpoint, Protocol, Sub URL, Additional Parameters, JDBC Url | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Project Id, Insight Id, Endpoint, Protocol |
      | Snowflake      | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Warehouse, Role, Database, Schema, Additional Parameters, JDBC Url                   | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Warehouse, Role, Database, Schema          |
      | SQL Server     | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Database, Schema, Additional Parameters, JDBC Url                                    | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | SQLITE         | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Additional Parameters, JDBC Url                                                      | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name                                             |
      | Teradata       | General | Catalog Name, Database Description, Tags | Settings | Host Name, Database, Additional Parameters, JDBC Url                                                  | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Database                                   |
      | Tibco          | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Schema, Additional Parameters, JDBC Url                                              | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Port, Schema                               |
      | Trino          | General | Catalog Name, Database Description, Tags | Settings | Host Name, Port, Catalog, Schema, Additional Parameters, JDBC Url                                     | Credentials | Username, Password                                           | Advanced Settings | Fetch Size, Connection Timeout, Pool Min Size, Pool Max Size | Catalog Name, Host Name, Port, Catalog, Schema                      |
