package aicore.unit.database.add;

import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import aicore.hooks.SetupHooks;
import aicore.pages.database.AddDatabaseFormUtils;
import aicore.pages.home.MainMenuUtils;
import aicore.utils.AbstractE2ETest;
import aicore.utils.AddDatabasePageUtils;

public class AddDatabaseFormValidationTests extends AbstractE2ETest {

	@BeforeAll
	public static void setup() throws IOException {
		login(page, UserType.NATIVE);
	}

	@ParameterizedTest(name = "Validate add database form for {0}")
	@MethodSource("databaseFormData")
	void testDatabaseForm(String dbType, Map<String, String[]> sections, String[] mandatoryFields) {
		MainMenuUtils.openMainMenu(SetupHooks.getPage());
		MainMenuUtils.clickOnOpenDatabase(SetupHooks.getPage());
		AddDatabaseFormUtils.clickAddDatabaseButton(page);
		AddDatabaseFormUtils.selectDatabaseFromConnectionTypes(page, dbType);

		// validate sections
		for (Map.Entry<String, String[]> entry : sections.entrySet()) {
			String sectionName = entry.getKey();
			String[] fields = entry.getValue();

			for (String field : fields) {
				boolean isFieldVisible = AddDatabasePageUtils.verifyFieldUnderSection(page, sectionName, field);
				Assertions.assertTrue(isFieldVisible, field + " is not visible under " + sectionName + " section");
			}
		}

		// validate mandatory fields
		for (String fieldName : mandatoryFields) {
			boolean isFieldMandatory = AddDatabaseFormUtils.isDBFieldMandatory(page, fieldName);
			Assertions.assertTrue(isFieldMandatory, fieldName + " is not mandatory field");
		}
	}

	// Code Generated by Sidekick is for learning and experimentation purposes only.
	@SuppressWarnings("unchecked")
	private static Stream<Arguments> databaseFormData() {
		return Stream.of(
				Arguments.of("Aster",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Athena",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Region", "Output", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Access Key", "Secret Key"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Output", "Access Key", "Secret Key" }),
				Arguments.of("BigQuery", sections(section("General", "Catalog Name", "Database Description", "Tags"),
						section("Settings", "Host Name", "Port", "Project", "Schema", "Additional Parameters",
								"JDBC Url"),
						section("Credentials", "OAuth Type", "OAuth Service Account", "OAuth Service Account Key")),
						new String[] { "Catalog Name", "Project", "OAuth Type" }),
				Arguments.of("Cassandra",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("ClickHouse",
						sections(
								section("General", "Catalog Name", "Database Description", "Tags"), section("Settings",
										"Host Name", "Port", "Database", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("DATABRICKS",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "HTTP Path", "Database", "Schema",
										"Additional Parameters", "JDBC Url"),
								section("Credentials", "UID", "Personal Access Token"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "HTTP Path", "UID" }),
				Arguments.of("DataStax",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "GRAPH"),
								section("Credentials", "Username", "Password")),
						new String[] { "Catalog Name", "Host Name", "GRAPH" }),
				Arguments.of("DB2",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Derby",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Elastic Search",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "HTTP Type", "Additional Parameters",
										"JDBC Url"),
								section("Credentials", "Username", "Password")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("H2",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Schema", "JDBC Url" }),
				Arguments.of("Hive",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Impala",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("MariaDB",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("MySQL",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Open Search",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "HTTP Path", "Additional Parameters",
										"JDBC Url"),
								section("Credentials", "Username", "Password")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Oracle",
						sections(
								section("General", "Catalog Name", "Database Description", "Tags"), section("Settings",
										"Host Name", "Port", "SID Service", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Phoenix",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Postgres",
						sections(
								section("General", "Catalog Name", "Database Description", "Tags"), section("Settings",
										"Host Name", "Port", "Database", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Database" }),
				Arguments.of("Redshift",
						sections(
								section("General", "Catalog Name", "Database Description", "Tags"), section("Settings",
										"Host Name", "Port", "Database", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Database" }),
				Arguments.of("SAP Hana",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Schema" }),
				Arguments.of("SEMOSS",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Project Id", "Insight Id", "Endpoint",
										"Protocol", "Sub URL", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Project Id", "Insight Id", "Endpoint",
								"Protocol" }),
				Arguments.of("Snowflake",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Warehouse", "Role", "Database", "Schema",
										"Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Warehouse", "Role", "Database", "Schema" }),
				Arguments.of("SQL Server",
						sections(
								section("General", "Catalog Name", "Database Description", "Tags"), section("Settings",
										"Host Name", "Port", "Database", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("SQLITE",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name" }),
				Arguments.of("Teradata",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Database", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Database" }),
				Arguments.of("Tibco",
						sections(section("General", "Catalog Name", "Database Description", "Tags"),
								section("Settings", "Host Name", "Port", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Port", "Schema" }),
				Arguments.of("Trino",
						sections(
								section("General", "Catalog Name", "Database Description", "Tags"), section("Settings",
										"Host Name", "Port", "Catalog", "Schema", "Additional Parameters", "JDBC Url"),
								section("Credentials", "Username", "Password"),
								section("Advanced Settings", "Fetch Size", "Connection Timeout", "Pool Min Size",
										"Pool Max Size")),
						new String[] { "Catalog Name", "Host Name", "Port", "Catalog", "Schema" }));
	}

	private static Map<String, String[]> sections(@SuppressWarnings("unchecked") Map.Entry<String, String[]>... entries) {
		Map<String, String[]> map = new LinkedHashMap<>();
		for (Map.Entry<String, String[]> entry : entries) {
			map.put(entry.getKey(), entry.getValue());
		}
		return map;
	}

	private static Map.Entry<String, String[]> section(String sectionName, String... fields) {
		return Map.entry(sectionName, fields);
	}

}
