######## UI does not have Privacy Information data. Hence commenting the some steps ######
Feature: Privacy Center Popup Validation

  Scenario: Validate Privacy Center popup and its elements
    Given User opens Main Menu
    When User clicks on Open Settings
    And User clicks on Privacy Center button
    Then Use can see Privacy popup with following elements
      | ELEMENT            | EXPECTED_NAME              |
      | Popup              |                            |
      | Popup name         | Privacy Preference Center  |
      | Close icon         |                            |
      | Close button       |                            |
      #| Title              | Privacy Information        |
      #| Section1           | Your Privacy               |
      #| Section2           | Strictly Necessary Cookies |
      #| Sub-section1       | First Party Cookies        |
      #| Sub-section2       | Third Party Cookies        |
      #| Cookie policy link |                            |
    #Then User should see the following cookie details
      #| NAME                  | HOST                                              | DURATION      | TYPE        | CATEGORY                   | DESCRIPTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      #| cfg-ai                | www.portal-jumpstart-ascend.deloitteinnovation.us | A few seconds | First Party | Strictly necessary cookies | Cookie from network layer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      #| OptanonConsent        | .portal-jumpstart-ascend.deloitteinnovation.us    | 365 Days      | First Party | Strictly necessary cookies | This cookie is set by the cookie compliance solution from OneTrust. It stores information about the categories of cookies the site uses and whether visitors have given or withdrawn consent for the use of each category. This enables site owners to prevent cookies in each category from being set in the users browser, when consent is not given. The cookie has a normal lifespan of one year, so that returning visitors to the site will have their preferences remembered. It contains no information that can identify the site visitor. |
      #| OptanonAlertBoxClosed | .portal-jumpstart-ascend.deloitteinnovation.us    | 365 Days      | First Party | Strictly necessary cookies | This cookie is set by websites using certain versions of the cookie law compliance solution from OneTrust. It is set after visitors have seen a cookie information notice and in some cases only when they actively close the notice down. It enables the website not to show the message more than once to a user. The cookie has a one year lifespan and contains no personal information.                                                                                                                                                        |
      #| monolith              | www.portal-jumpstart-ascend.deloitteinnovation.us | Session       | First Party | Strictly necessary cookies | This cookie is used for user session management.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      #| fpc                   | login.microsoftonline.com                         | 1 Month       | Third Party | Strictly necessary cookies | This cookie is set by Microsoft for secure authentication of the user's login details.                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| stsservicecookie      | login.microsoftonline.com                         | Session       | Third Party | Strictly necessary cookies | Azure Active Directory B2C authentication-related cookie.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      #| x-ms-gateway-slice    | login.microsoftonline.com                         | Session       | Third Party | Strictly necessary cookies | This cookie is set by Microsoft for secure authentication of the user's login details.                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      #| esctx-xxxxxxxxxxx     | login.microsoftonline.com                         | 1 Day         | Third Party | Strictly necessary cookies | This cookie is written to help with site security in preventing Cross-Site Request Forgery attacks.                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      #| esctx                 | login.microsoftonline.com                         | Session       | Third Party | Strictly necessary cookies | Session context cookie information. For CSRF protection. Binds a request to a specific browser instance so the request can't be replayed outside the browser. No user information.                                                                                                                                                                                                                                                                                                                                                                  |
    #When User clicks on Cookie policy link
    #Then User navigates to 'https://cookienotice.deloitte.com/' page
    When User clicks on Close icon
    Then Privacy popup should close
    And User clicks on Privacy Center button
    When User clicks on 'Close' button
    Then Privacy popup should close
